/****************************************************************************************************
	EBNObservableCollections.h
	Observable

    Created by Chall Fry on 5/13/14.
    Copyright (c) 2013-2014 eBay Software Foundation.
*/

/**
	A mutable dictionary whose keys can be observed. Acts as a NSMutableDictionary. Allows observations
	to be created on dictionary keys, as if they were properties. This includes using keypaths
	that have an EBNObservableDictionary as an element in the keypath.
	
	This collection object also makes count into a property; this property is observable.
 */
@interface EBNObservableDictionary : NSMutableDictionary

@property (readonly)		NSUInteger count;

@end

/**
 	An mutable array whose array indices can be observed. EBNObservableArray supports two ways to observe array elements.
	
	First, array elements can be observed with a keypath element syntax where the array index is the property
	name; for example "4". This observation style is called "object-following", and will follow the object 
	currently at index 4 in the array, notifying when that object is removed from the array. 
	
	Second, array elements can be observed with a "#4" style syntax, which creates an "index-following" observation.
	This observation will be triggered when ever the object at index 4 in the array changes. This style of observation
	can be initiaed on array elements beyond the current end of the array.

	This collection object also makes count into a property; this property is observable.
*/
@interface EBNObservableArray : NSMutableArray

@property (readonly)		NSUInteger count;

@end


/**
	A mutable set whose elements can be observed. EBNObservableSet uses keyForObject: to create strings for set
	elements that can be added to keypaths. Observations on set elements will be triggered when the the
	observed element is added or removed from the set. Observations only get called if the set actually mutates.

	This collection object also makes count into a property; this property is observable.
*/
@interface EBNObservableSet : NSMutableSet

@property (readonly)		NSUInteger count;


/**
	Creates a key path element string from a object. This string may be inserted into a keypath in order to
	observe changes to a set's elements.
	
	Object does not have to be an element of a set to use this method. If you create an observation on a set with
	a keypath based on the result of this method (when called for an object A), and then add object A to the set,
	the observation will be triggered.
	
	The generated string is based on [object hash].

	@param object The object to use when creating the string

	@return A string
 */
+ (NSString *) keyForObject:(id) object;

/**
	Returns the object in the set that matches the key, where key was created by keyForObject:.
	
	If no member of the set matches key, returns nil. This means that objectForKey: cannot find an object that
	was removed from a set.

	@param key A string generated by keyForObject:

	@return A set member, or nil.
 */
- (id) objectForKey:(NSString *) key;

@end
