/****************************************************************************************************
	NSSet+EBNObservable.h
	Observable

 	Created by Chall Fry on 2/22/16.
	Copyright © 2013-2018 eBay Software Foundation.
*/

#import <Foundation/Foundation.h>


@interface NSSet (EBNObservable)

/**
	If you want to observe when an object enters/leaves a set with Observable, you need a way to refer
	the the object you're interested in with a string. Sets don't normally have a way to do this. This
	is what ebn_keyForObject is for.
	
	This method takes an object which may or may not be in a set already, and returns a string that can
	be placed into a keypath. This string is based on the hash result for the object, which means it's
	possible your observation on a set object will be called spuriously due to a hash collision.
*/
+ (nonnull NSString *) ebn_keyForObject:(nonnull id) object;

/**
	This method is here mostly to support unit testing. Due to the possibility of hash collisions, this
	should not be used as a method of reliably getting objects out of sets.
	
	Given a key generated by ebn_keyForObject, returns an object in the set that matches the key, else null.
	
	I'm going to say this again: Sets are not dictionaries. They are NOT a key-value store. Think carefully
	before using this.
*/
- (nullable id) ebn_objectForKey:(nullable NSString *) key;

@end
